# Tools
ABC:            ["abc_with_bb_support", "abc"]
ACE2:           ["ace2"]
blifexplorer:   ["blifexplorer"]
Odin:           ["ODIN_II", "odin2_helper"]
VPR:            ["vpr"]

# Libraries
libarchfpga:    ["libs/libarchfpga"]
libeasygl:      ["libs/libeasygl"]
liblog:         ["libs/liblog"]
libpugiutil:    ["libs/libpugiutil"]
libvtrutil:     ["libs/libvtrutil"]
external_libs:  ["libs/EXTERNAL"]

# General areas
docs:      ["docs/", "README.md", "*.md", "tutorial", "README", "*.rst"]
infra:     [".travis.yml", ".travis.yml", ".travis/", "scripts/", ".github/", "Dockerfile"]
build:     ["Makefile", "*.make", "CMakeLists.txt", "cmake"]
tests:     ["*_test.pl", "*test*", "*TESTS*"]
scripts:   ["scripts", "*.pl", "*.sh"]
VTR Flow:  ["vtr_flow"]

# Tag pull requests with the languages used to make it easy to see what is
# being used.
lang-hdl:       ["*.v", "*.sv"]
lang-cpp:       ["*.c*", "*.h"]
lang-perl:      ["*.pl", "*perl*"]
lang-python:    ["*.py"]
lang-shell:     ["*.sh"]
lang-netlist:   ["*.blif", "*.eblif", "*.edif"]
lang-make:      ["*.make", "Makefile", "CMakeLists.txt"]
